/* Alias; AS
*/

SELECT DISTINCT
    salary_currency AS unique_currency
FROM
    data_jobs;

-- count the distinct salary_currency    
SELECT 
    COUNT (DISTINCT salary_currency)
FROM
    data_jobs;

-- give it a nicer alias
-- count the distinct salary_currency    
SELECT 
    COUNT (DISTINCT salary_currency) AS number_currencies
FROM
    data_jobs;

-- alias that is generated by a built-in function
SELECT
    ROW_NUMBER() OVER AS id,
    * 
FROM
    data_jobs